version: '3'
services:
  backend-example-app:
    image: backend-app:1.0
    networks:
      - backend-facade-keycloak
    build: ./backend-example-app
    container_name: backend-app
    restart: always
    ports:
      - "8080:8080"

  idp-facade:
    image: idp-facade:1.0
    networks:
      - backend-facade-keycloak
    build: ./idp-facade
    container_name: idp-facade
    restart: always
    ports:
      - "8090:8090"

  keycloak:
    image: jboss/keycloak:16.1.1
    networks:
      - backend-facade-keycloak
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data/
      - ./keycloak/realms/kcrealm.json:/tmp/realm-export.json
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/tmp/realm-export.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
      - "-Djboss.socket.binding.port-offset=100"
    ports:
      - "8180:8180"

volumes:
  keycloak-data:
    driver: local

networks:
  backend-facade-keycloak:

