user-info-uri: http://localhost:8180/auth/realms/idp-provider/protocol/openid-connect/userinfo
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: idp-provider
  resource: idp-facade
  public-client: 'false'
  bearer-only: 'true'
token-uri: http://localhost:8180/auth/realms/idp-provider/protocol/openid-connect/token
endpoints-uri: http://localhost:8180/auth/realms/idp-provider/.well-known/openid-configuration
logout: http://localhost:8180/auth/realms/idp-provider/protocol/openid-connect/logout
client-secret: NfPFBF9Cjqfpd7GcOH6uVVQ9EevZHfBf
server:
  port: '8090'
introspect-uri: http://localhost:8180/auth/realms/idp-provider/protocol/openid-connect/token/introspect



