facade:
  userinfo-url: http://localhost:8090/userinfo
  introspect-url: http://localhost:8090/introspect
  logout-url: http://localhost:8090/logout
  token-url: http://localhost:8090/token
  protected-url: http://localhost:8090/userinfo

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
       enabled: 'true'
       path: /h2