facade:
  userinfo-url: http://localhost:8090/userinfo
  introspect-url: http://localhost:8090/introspect
  logout-url: http://localhost:8090/logout
  token-url: http://localhost:8090/token
  protected-url: http://localhost:8090/userinfo

#spring:
#  datasource:
#    username: sa
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    password: ''
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#       enabled: 'true'
#       path: /h2

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: idp-provider
  resource: idp-facade
  public-client: 'true'
  security-constraints[0]:
    -authRoles[0]: admin
    -securityCollections[0]:
      -patterns[0]: /protected