apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: idp-facade
spec:
  selector:
    matchLabels:
      app: idp-facade
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: idp-facade
    spec:
      containers:
        - name: idp-facade
          image: idp-facade:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090 # The port that the container is running on in the cluster
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: idp-facade
spec:
  selector:
    app: idp-facade
  ports:
    - protocol: "TCP"
      nodePort: 31001
      port: 8090 # The port that the service is running on in the cluster
      targetPort: 8090 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.

